% write_fade_hpp.m
% writes out the fader random variables to a C++ header file for HLS.

function [retval] = write_fader_hpp (states, filename)

    N = size(states.theta, 1);
    M = size(states.Phi, 3);
    
    fp = fopen(filename, 'w');
    fprintf(fp, '// %s\n', filename);
    fprintf(fp, '// This file autogenerated to provide the "states" structure for the HLS C++ fader.\n\n');   
    
    
%    fprintf(fp, 'typedef struct {\n');
%    fprintf(fp, '    fade_type phi_real[%d];\n', M);
%    fprintf(fp, '    fade_type phi_imag[%d];\n', M);
%    fprintf(fp, '    fade_type cos_alpha[%d];\n', M);
%    fprintf(fp, '    fade_type sin_alpha[%d];\n', M);
%    fprintf(fp, '} rand_state;\n');

    fprintf(fp, 'const rand_state state[%d] = {\n', N);
    
    for i=1:N
        fprintf(fp, '    // channel = %d\n', i-1);
    end
    
    fprintf(fp, '}\n');
    
    
    fclose(fp);

endfunction
